services:
  - type: web
    name: dukaSeguros
    env: python
    buildCommand: ""
    startCommand: gunicorn nome_do_projeto.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nome_do_projeto.settings
      - key: SECRET_KEY
        value: sua_secret_key
      - key: DEBUG
        value: False
