# Generated by Django 5.2.1 on 2025-05-26 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(choices=[('AUTO', 'Automóvel'), ('VIDA', 'Vida'), ('SAUDE', 'Saúde'), ('RESIDENCIAL', 'Residencial'), ('EMPRESARIAL', 'Empresarial'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=200)),
                ('documento', models.CharField(help_text='CPF ou CNPJ', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Apolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('RENOVADA', 'Renovada')], default='ATIVA', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apolices_cadastradas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apolices', to='core.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apolices', to='core.produto')),
            ],
            options={
                'verbose_name': 'Apólice',
                'verbose_name_plural': 'Apólices',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administradora', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('IMOVEL', 'Imóvel'), ('AUTOMOVEL', 'Automóvel'), ('MOTO', 'Motocicleta'), ('CAMINHAO', 'Caminhão'), ('MAQUINAS', 'Máquinas e Equipamentos'), ('OUTROS', 'Outros')], max_length=20)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('cota', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_parcelas', models.PositiveIntegerField()),
                ('parcelas_pagas', models.PositiveIntegerField(default=0)),
                ('data_adesao', models.DateField()),
                ('data_contemplacao', models.DateField(blank=True, null=True)),
                ('taxa_administracao', models.DecimalField(decimal_places=2, help_text='Percentual', max_digits=5)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONTEMPLADO', 'Contemplado'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consorcios_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consorcios', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Consórcio',
                'verbose_name_plural': 'Consórcios',
                'ordering': ['-data_adesao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('BOLETO', 'Boleto'), ('CARTAO', 'Cartão de Crédito'), ('DEBITO', 'Débito Automático'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('DINHEIRO', 'Dinheiro')], max_length=15)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('parcela', models.PositiveSmallIntegerField(default=1)),
                ('total_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('apolice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.apolice')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['apolice', 'data_vencimento'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='seguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.seguradora'),
        ),
    ]
