# Generated by Django 5.2.1 on 2025-05-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_administradoraconsorcio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consorcio',
            name='administradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.administradoraconsorcio'),
        ),
    ]
