# Generated by Django 5.2.1 on 2025-09-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolice',
            name='produto',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('MOTO', 'MOTO'), ('RESIDENCIAL', 'RESIDENCIAL'), ('CONDOMINIO', 'CONDOMÍNIO'), ('EMPRESARIAL', 'EMPRESARIAL'), ('VIDA', 'VIDA'), ('FIANCA', 'FIANÇA'), ('FROTA', 'FROTA'), ('PORTATEIS', 'PORTÁTEIS'), ('VIAGEM', 'VIAGEM'), ('IMOBILIARIA', 'IMOBILIÁRIA'), ('BIKE', 'BIKE'), ('RESPONSABILIDADE_CIVIL', 'RESPONSABILIDADE CIVIL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apolice',
            name='status',
            field=models.CharField(choices=[('PROPOSTA', 'Proposta'), ('APROVADA', 'Proposta Aprovada'), ('ATIVA', 'Ativa'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada'), ('VENCIDA', 'Vencida'), ('RENOVADA', 'Renovada')], default='PROPOSTA', max_length=10),
        ),
    ]
