# Generated by Django 5.2.1 on 2025-09-15 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_apolice_produto_alter_apolice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administradoraconsorcio',
            options={'ordering': ['nome'], 'verbose_name': 'Administradora de Consórcio', 'verbose_name_plural': 'Administradoras de Consórcios'},
        ),
        migrations.AddField(
            model_name='apolice',
            name='protocolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apolice',
            name='seguradora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apolices', to='core.seguradora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='apolice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.apolice'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='consorcio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consorcio'),
        ),
        migrations.AlterField(
            model_name='apolice',
            name='produto',
            field=models.CharField(choices=[('AUTO', 'AUTO'), ('MOTO', 'MOTO'), ('RESIDENCIAL', 'RESIDENCIAL'), ('CONDOMINIO', 'CONDOMÍNIO'), ('EMPRESARIAL', 'EMPRESARIAL'), ('VIDA', 'VIDA'), ('FIANCA', 'FIANÇA'), ('FROTA', 'FROTA'), ('PORTATEIS', 'PORTÁTEIS'), ('VIAGEM', 'VIAGEM'), ('IMOBILIARIA', 'IMOBILIÁRIA'), ('BIKE', 'BIKE'), ('RESP_CIVIL', 'RESPONSABILIDADE CIVIL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='apolice',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('NAO_ATIVO', 'Não Ativo'), ('PENDENTE', 'Pendente'), ('ENDOSSO', 'Endosso')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consorcio',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('NAO_ATIVO', 'Não Ativo'), ('PENDENTE', 'Pendente'), ('ENDOSSO', 'Endosso')], default='ATIVO', max_length=15),
        ),
    ]
