# Generated by Django 5.2.1 on 2025-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_administradoraconsorcio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='apolice',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='consorcio',
        ),
        migrations.AddField(
            model_name='apolice',
            name='classificacao_bonus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação de Bônus'),
        ),
        migrations.AddField(
            model_name='apolice',
            name='codigo_ci',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código C.I'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
